// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"
)

type Book struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Author      string    `json:"author"`
	Year        int32     `json:"year"`
	Masterpiece bool      `json:"masterpiece"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
