// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countBooks = `-- name: CountBooks :one
SELECT COUNT(*)
FROM books
WHERE 1=1
  AND (CASE WHEN $1::text IS NOT NULL THEN author ILIKE '%' || $1 || '%' ELSE true END)
  AND (CASE WHEN $2::int IS NOT NULL THEN year = $2::int ELSE true END)
  AND (CASE WHEN $3::boolean IS NOT NULL THEN masterpiece = $3::boolean ELSE true END)
`

type CountBooksParams struct {
	FilterAuthor      sql.NullString `json:"filter_author"`
	FilterYear        sql.NullInt32  `json:"filter_year"`
	FilterMasterpiece sql.NullBool   `json:"filter_masterpiece"`
}

func (q *Queries) CountBooks(ctx context.Context, arg CountBooksParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countBooks, arg.FilterAuthor, arg.FilterYear, arg.FilterMasterpiece)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (name, author, year, masterpiece)
VALUES ($1, $2, $3, $4)
RETURNING id, name, author, year, masterpiece, created_at, updated_at
`

type CreateBookParams struct {
	Name        string `json:"name"`
	Author      string `json:"author"`
	Year        int32  `json:"year"`
	Masterpiece bool   `json:"masterpiece"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Name,
		arg.Author,
		arg.Year,
		arg.Masterpiece,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Year,
		&i.Masterpiece,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :execrows
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteBook, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBookByID = `-- name: GetBookByID :one
SELECT id, name, author, year, masterpiece, created_at, updated_at
FROM books
WHERE id = $1
`

func (q *Queries) GetBookByID(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByID, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Year,
		&i.Masterpiece,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, name, author, year, masterpiece, created_at, updated_at
FROM books
WHERE 1=1
  AND (CASE WHEN $1::text IS NOT NULL THEN author ILIKE '%' || $1 || '%' ELSE true END)
  AND (CASE WHEN $2::int IS NOT NULL THEN year = $2::int ELSE true END)
  AND (CASE WHEN $3::boolean IS NOT NULL THEN masterpiece = $3::boolean ELSE true END)
ORDER BY 
  CASE WHEN $4::text = 'name' THEN name END,
  CASE WHEN $4::text = 'author' THEN author END,
  CASE WHEN $4::text = 'masterpiece' THEN masterpiece::text END
LIMIT $6 OFFSET $5
`

type ListBooksParams struct {
	FilterAuthor      sql.NullString `json:"filter_author"`
	FilterYear        sql.NullInt32  `json:"filter_year"`
	FilterMasterpiece sql.NullBool   `json:"filter_masterpiece"`
	SortBy            string         `json:"sort_by"`
	PageOffset        int32          `json:"page_offset"`
	PageLimit         int32          `json:"page_limit"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, listBooks,
		arg.FilterAuthor,
		arg.FilterYear,
		arg.FilterMasterpiece,
		arg.SortBy,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Author,
			&i.Year,
			&i.Masterpiece,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET name = $1, author = $2, year = $3, masterpiece = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $5
RETURNING id, name, author, year, masterpiece, created_at, updated_at
`

type UpdateBookParams struct {
	Name        string `json:"name"`
	Author      string `json:"author"`
	Year        int32  `json:"year"`
	Masterpiece bool   `json:"masterpiece"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.Name,
		arg.Author,
		arg.Year,
		arg.Masterpiece,
		arg.ID,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Author,
		&i.Year,
		&i.Masterpiece,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
